
PORT = 5500
###
DELETE http://localhost:5500/api/data/
###
GET  http://localhost:5500/
###

POST http://localhost:5500/auth/register/
Content-Type: application/json

{
    "username": "cku25@gmail.com", "password":"coder"
}

###
POST http://localhost:5500/auth/login/
Content-Type: application/json

{
    "username": "cku24@gmail.com", "password":"coder"
}

### TO DO
GET  http://localhost:5500/todos
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNzcxMzI1ODYwLCJleHAiOjE3NzE0MTIyNjB9.W3aiV_X5IasQphD68b7nA9t0GviONMHcbiIVmgFCCus

### ADD TODO
POST  http://localhost:5500/todos
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNzcxMzI1ODYwLCJleHAiOjE3NzE0MTIyNjB9.W3aiV_X5IasQphD68b7nA9t0GviONMHcbiIVmgFCCus
Content-Type: application/json

{
    "task": "The last one"
}