
PORT = 5500
###
DELETE http://localhost:5500/api/data/
###
GET  http://localhost:5500/
###

POST http://localhost:5500/auth/register/
Content-Type: application/json

{
    "username": "cku24@gmail.com", "password":"coder"
}

###
POST http://localhost:5500/auth/login/
Content-Type: application/json

{
    "username": "cku24@gmail.com", "password":"coder"
}

### TO DO
GET  http://localhost:5500/todos
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzcxMjE0MjMzLCJleHAiOjE3NzEzMDA2MzN9.cRJwQrX41EmdIazAh1pAAg4dI6mb9EEM35D2_3VsjuU

